name: CI-CD Pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 |
        docker login --username AWS --password-stdin YOUR_ECR_URI
    - name: Build Docker image
      run: |
        docker build -t groww-app ./docker
        docker tag groww-app:latest YOUR_ECR_URI:latest
    - name: Push image
      run: |
        docker push YOUR_ECR_URI:latest
